version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sporchestratorapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "9000:80"
    restart: unless-stopped
    networks:
      appnetwork:
        ipv4_address: 172.22.0.2

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8080:80"  # Mapea el puerto 8080 del host al puerto 80 del contenedor
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped
    networks:
      appnetwork:
        ipv4_address: 172.22.0.3

networks:
  appnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
