name: .NET Build, Test and Deploy to IIS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: dotnet publish SPOrchestratorAPI.csproj -c Release -o ./publish --no-restore

      # Paso de despliegue usando MSDeploy
      - name: Deploy to IIS Server via MSDeploy
        run: |
          msdeploy.exe -verb:sync `
            -source:contentPath="./publish" `
            -dest:contentPath="SPOrchestratorAPI",computerName="https://$env:DEPLOY_SERVER:8172/msdeploy.axd",userName="$env:DEPLOY_USER",password="$env:DEPLOY_PASS",authType="Basic" `
            -allowUntrusted
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}   # Ej: 192.168.1.100
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASS: ${{ secrets.DEPLOY_PASS }}